# Generated by Django 5.1.6 on 2025-03-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_table',
            new_name='CourseTable',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
